/**
 * 每日鼓励语池 — 365 句英语二次元少女励志语录
 * 按年内天数轮换（dayOfYear % 365），方便自定义：
 *   直接在下方数组中增删改句子即可，无需修改 content.js
 */
window.CAT_CHEER_PHRASES = [
    // ── 1–30  新的一天 ──────────────────────────────────────
    "You can do it! I just know you can, senpai~!",
    "Kyaa~! You're doing so amazing today!",
    "Don't give up! I'm always rooting for you~!",
    "You're my favorite person, so believe in yourself!",
    "Oh my gosh, you're literally the best! Keep going~!",
    "Ehehe~ Today is YOUR day, I can feel it!",
    "You shine so bright! Never stop being awesome~!",
    "Yay yay yay! You're doing super amazing today!",
    "I believe in you with my whole heart~!",
    "You're incredible! Like, seriously incredibly awesome!",
    "Nyan~! Every little step counts! You're doing great!",
    "Keep smiling and shining! You're my hero~!",
    "Uwaa~ You worked so hard! I'm so proud of you!",
    "You're like a shooting star — so bright and beautiful!",
    "Hey hey! Don't forget: you're absolutely wonderful~!",
    "You've got the cutest determination! Nothing can stop you!",
    "Sugoi~! You're growing stronger every single day!",
    "Mou, stop doubting yourself! You're amazing, okay~?!",
    "Every day you try your best makes the world happier!",
    "Fufufu~ I knew you had it in you all along!",
    "Chase your dreams with all your heart! I'll cheer for you~!",
    "You make me so happy just by being you! Keep it up!",
    "Wahh~! Today's challenge is no match for someone like you!",
    "You've got this! And if you stumble, I'll catch you~!",
    "Shine on, you beautiful, hardworking soul~!",
    "Ufufufu~ Look at you go! So cool, so amazing!",
    "Hey, take a deep breath. You've got all the strength you need!",
    "I'm your number one fan, and I say you're unbeatable~!",
    "Ooh ooh! Something wonderful is heading your way today~!",
    "You're like cherry blossoms — beautiful and full of life!",
    // ── 31–60  坚持与毅力 ────────────────────────────────────
    "Tehe~ Even on hard days, your effort is so precious!",
    "You're writing your own amazing story! Keep going~!",
    "Wow, look how far you've come! I'm so, so proud!",
    "Ne ne~ Promise me you'll smile today, okay? You deserve it!",
    "Your best is always good enough! Never forget that~!",
    "You're a little fighter with a big heart! Love you~!",
    "Waai~! A brand new day full of possibilities, just for you!",
    "You make difficult things look easy! How do you even do that~?",
    "Stay sparkly, stay strong, stay you! The world needs more of you!",
    "Hehe~ You're one step closer to your dream today!",
    "I see how hard you try every day. It means everything~!",
    "You give me so much inspiration! Now go out there and shine~!",
    "Everything you do is filled with love and effort — it shows~!",
    "Ara ara~ Don't push too hard, but you've SO got this!",
    "You're not just trying, you're succeeding! Believe that~!",
    "Each day you get a little stronger, a little brighter — so cool!",
    "You're my sunshine on a cloudy day! Keep being wonderful~!",
    "Nee nee! Your hard work is going to pay off, I just know it!",
    "You are loved, you are capable, you are unstoppable~!",
    "Ahh, you're doing it! You're really doing it! So proud~!",
    "Smile! The world is better because you're in it today~!",
    "You're incredible, and I'll keep saying it until you believe me~!",
    "Whatever comes today, you can handle it with grace and style~!",
    "Your journey is unique and beautiful — own every step~!",
    "Hiyaa~! Today's problems don't stand a chance against you!",
    "You've conquered hard things before — this is nothing new~!",
    "I get so happy thinking about how much you've grown~!",
    "You are doing wonderfully — even when it doesn't feel like it!",
    "Start fresh, stay bright, and bloom today~! You've got this!",
    "Every effort you make today plants a seed for tomorrow~!",
    // ── 61–90  自我认同 ──────────────────────────────────────
    "You are seen, you are valued, and you are so very capable~!",
    "Ne, guess what? You're doing better than you think! Really~!",
    "There's magic in your determination — I can totally see it~!",
    "Your smile can light up the whole room! Don't hold it back~!",
    "Keep going, keep glowing — you're almost there, I promise~!",
    "Waaah, today is going to be your best day ever! I just know it~!",
    "You're the main character of your own story — make it epic~!",
    "Even if it's tough, you're tougher! Ganbare, my favorite person~!",
    "Every morning you wake up is another chance to be amazing~!",
    "Hm hm hm~ I can already tell today is going to be wonderful for you!",
    "You radiate such good energy — the universe is definitely on your side~!",
    "When you feel like giving up, remember I'm cheering for you always~!",
    "You have such a kind and strong heart — I admire you so much~!",
    "Your courage is showing today and it looks absolutely lovely~!",
    "Teehee~ Even your mistakes are part of your beautiful journey!",
    "The fact that you try every day makes you my absolute hero~!",
    "You deserve every good thing coming your way — receive it with joy~!",
    "I love how you never stop trying even when things get hard~!",
    "You bring light wherever you go — please never dim your shine~!",
    "Hehe, dreams don't work unless you do, and look at you working~!",
    "One kind thought, one brave step — that's all it takes today~!",
    "You're not behind! You're exactly where you need to be~!",
    "Maa maa~ Breathe, smile, and remember: you are absolutely enough!",
    "Your potential is limitless — I see it so clearly from here~!",
    "It's okay to rest, but never quit! You've come so far~!",
    "You were made for great things — don't ever let anyone tell you otherwise~!",
    "Eeeek! I got so excited imagining all the great things you'll do today~!",
    "Today's a new page — write something beautiful on it~!",
    "You handle everything with such elegance — honestly, wow~!",
    "Even the smallest victory counts! I'm celebrating every single one with you~!",
    // ── 91–120  梦想与未来 ────────────────────────────────────
    "Your dedication is breathtaking — it really, truly is~!",
    "You are a whole universe of wonderful things — explore yourself with love~!",
    "Good morning! Today's mission: be kind to yourself and conquer one thing~!",
    "Waku waku~! The excitement I feel about your future is through the roof!",
    "Every challenge you face is secretly an opportunity in disguise~!",
    "You don't have to be perfect — just keep being authentically, wonderfully you~!",
    "Hah, as if anything could keep you down for long! You always bounce back~!",
    "You are the protagonist and this is your glow-up arc~!",
    "Whatever today brings, you have the power to handle it beautifully~!",
    "Your resilience is one of the most beautiful things about you~!",
    "Uwuu~ The world is lucky to have someone like you in it!",
    "Keep your chin up! Beautiful things are just around the corner~!",
    "Nee, do you know how exceptional you really are? Let me count the ways~!",
    "Shining through the hard moments makes you even more brilliant — keep going~!",
    "I pinky promise: your hard work will one day make you cry happy tears~!",
    "Trust the process! Amazing things are being built inside you right now~!",
    "You are absolutely full of magic — let a little bit out today~!",
    "Hey, not everyone could do what you do — you're truly special~!",
    "Waaaah you're so cool! Have you seen yourself lately? Stunning soul energy~!",
    "Take each step with confidence — every single one is leading somewhere great~!",
    "You're like a rare flower blooming in its own perfect season~!",
    "Don't compare your chapter one to someone else's chapter twenty~!",
    "Mhm mhm~ Your growth this year alone has been absolutely remarkable~!",
    "Even on the days when nothing works, YOU still work — and that matters~!",
    "Your kindness is a superpower — please never stop using it~!",
    "You overflow with warmth and talent — the world needs all of it~!",
    "Yosh! Today, you take one step closer to your most wonderful self~!",
    "Your dreams are valid, your feelings are valid, and YOU are valid~!",
    "Iya~ Stop being so hard on yourself! You're doing an incredible job~!",
    "Just showing up every day takes tremendous courage — and you do it~!",
    // ── 121–150  温柔鼓励 ────────────────────────────────────
    "Let your light shine today — even if it flickers, it's still beautiful~!",
    "Hnn~ Growth is hard, but you make it look so graceful~!",
    "You are genuinely one of a kind — there's no one else quite like you~!",
    "The universe is conspiring in your favor right now, can you feel it~?",
    "Wow, you handled that so well! You should be incredibly proud~!",
    "Saa~ Time to show the world what you're made of today~!",
    "Your effort today is building the life of your dreams — piece by piece~!",
    "You have everything inside you to make today wonderful~!",
    "Dokidoki~! I get so excited thinking about all you're going to achieve~!",
    "You face every day with such bravery — that's truly extraordinary~!",
    "Be gentle with your heart today — it works so incredibly hard~!",
    "Rise like the sun — warm, bright, and impossible to ignore~!",
    "Ara~ You're going to look back on today and smile, I just know it~!",
    "You're not stuck, you're growing roots — the blooming comes next~!",
    "Your perseverance is quietly rewriting your future — I can see it~!",
    "Happy thoughts, big dreams, small steps — that's your recipe for magic~!",
    "Yoisho~! Watch out world, this amazing person is on their way~!",
    "You hold so much power within you — trust it more each day~!",
    "Ne, I think you forget sometimes how absolutely remarkable you are~!",
    "Each good habit you build today is a gift to your future self~!",
    "Fufu~ You're more capable than your most anxious thoughts suggest~!",
    "Breathe in confidence, breathe out doubt — you've got this~!",
    "Your story is still being written — the best chapters are ahead~!",
    "Ehhh, did you really just do that? That was so amazing and brave~!",
    "You face the unknown with such grace — it's genuinely inspiring~!",
    "Today, you're not just surviving — you're absolutely thriving~!",
    "Whatever yesterday was, today is brand new and full of hope~!",
    "You are always, always worthy of love and success — please remember that~!",
    "Nyan nyan~! Your energy today is absolutely electric and irresistible~!",
    "Keep believing in yourself the way I believe in you — fiercely~!",
    // ── 151–180  活力与能量 ──────────────────────────────────
    "Shining bright even through storm clouds is what you do best~!",
    "You've survived every hard day so far — perfect track record~!",
    "Suki suki~! I love how determined and passionate you are about your dreams~!",
    "One day you'll tell your story and inspire someone who needed it~!",
    "You are a walking, talking miracle — please treat yourself accordingly~!",
    "Mou~! Stop underselling yourself! You are genuinely extraordinary~!",
    "There's a fire in you that nothing can extinguish — keep fanning it~!",
    "Hmmmm~ I wonder if you realize just how much you've accomplished already~!",
    "Today is a chance to be even more amazing than yesterday — seize it~!",
    "You're growing into someone truly wonderful — I'm watching with awe~!",
    "Push a little further today — the view from the next level is stunning~!",
    "Uwaaah! You make everything look so easy and effortless — how~?!",
    "Your comeback story is going to be legendary — I believe it fully~!",
    "Dekiru dekiru~! You can do it, you can do it, believe believe believe~!",
    "Put your whole heart into today — it deserves nothing less from you~!",
    "You are the energy in a room — bright, warm, and irreplaceable~!",
    "Heyyy~ Don't let the tough moments define you, let them refine you~!",
    "You were designed for brilliance — everything else is just warm-up~!",
    "Someone out there is inspired by how you keep going — keep going~!",
    "Fuwa fuwa~! Float above the noise and just do your magical best today~!",
    "You are proof that beauty, strength, and determination can coexist~!",
    "Doki doki~ I believe in your dreams even on the days you can't~!",
    "This is your season to bloom — let nothing stop you from growing~!",
    "You are strong enough, smart enough, and worthy enough — always~!",
    "Ara ara~ My, my, look at how far you've come, darling~!",
    "Kira kira~! Your future is sparkling and waiting for you to arrive~!",
    "Every tiny act of courage adds up to an extraordinary life~!",
    "You radiate a kind of rare, genuine warmth — please keep sharing it~!",
    "Ehh~ Are you really going to let this stop you? I don't think so~!",
    "No matter what today brings, your heart is big enough to handle it~!",
    // ── 181–210  中段加油 ────────────────────────────────────
    "You are deeply loved and wildly capable — time to act like it~!",
    "Saa saa~ One step at a time, you build mountains~!",
    "Your good energy is contagious — spread it freely and shamelessly~!",
    "Nono~! Don't count your failures, count your lessons — they're precious~!",
    "You have a special gift the world won't find anywhere else — you~!",
    "Yoisho! Time to rise, shine, and absolutely slay the day~!",
    "Believe in the magic of your own hard work — it's very, very real~!",
    "Cheering for you doesn't get old — I'll never stop, not ever~!",
    "Aa~ The strength you've shown just to get here deserves applause~!",
    "Your quiet determination moves mountains — keep moving them~!",
    "Make today so good that yesterday becomes jealous~!",
    "Fufu~ Great things take time, and great things are coming for you~!",
    "You deserve every wonderful thing — don't let anyone convince you otherwise~!",
    "Life is better, brighter, and more colorful because you're in it~!",
    "New day, same amazing you — but slightly more powerful~!",
    "Hoho~! Watch that person level up in real time — oh wait, that's you~!",
    "You're not just reaching for your dreams — you're already living parts of them~!",
    "Ooh, that nervous energy you feel? That's your passion knocking~!",
    "You are someone worth knowing, worth loving, worth celebrating — daily~!",
    "Mhm~ Your presence makes every space you enter just a little bit better~!",
    "Overcome and outshine — that's the only mode you know~!",
    "Fuwaaaa~! You're so close to something incredible — keep reaching~!",
    "Your focus and drive could power a whole city — use that energy today~!",
    "Ehehehe~ Did I mention lately that you're completely and utterly amazing~?",
    "You have climbed hills before — today's hill is no different~!",
    "Ne ne ne~ Your effort is noticed, appreciated, and so very worth it~!",
    "Oooh, the day ahead is full of opportunities waiting for someone like you~!",
    "You paint your world with your choices — make today's palette beautiful~!",
    "Mmm~ Setbacks are just the plot twists that make the story richer~!",
    "You are growing in ways you can't even fully see yet — trust it~!",
    // ── 211–240  成长与蜕变 ──────────────────────────────────
    "Hehe, the best version of yourself is already in there — let them out~!",
    "Grab today by the hands and dance — you were made for joy~!",
    "Uwuuu~! My heart swells with pride at how far you have come~!",
    "Your grit and grace together are a force of nature — magnificent~!",
    "Iya iya iya~ You are NOT giving up, because you don't do that~!",
    "Today's you is stronger and wiser than yesterday's you — build on that~!",
    "Soaring through life with a smile looks perfect on you~!",
    "Hm~ Every seed of effort you plant today will flower when you least expect it~!",
    "You are a whole adventure wrapped inside one incredible person~!",
    "Rest if you must, but never settle — you deserve the whole dream~!",
    "Naa~! The version of you from last year would be so proud right now~!",
    "Your gentle strength is the most powerful kind — don't doubt it~!",
    "Tomorrow will thank you for not giving up today~!",
    "Kyun~! My heart does a little jump thinking about how amazing you are~!",
    "The sparkle in your eyes when you talk about your dreams — chase that~!",
    "You are writing history one brave small step at a time~!",
    "Ahaha~! Nothing stops you for long — you just keep going, beautifully~!",
    "Today's challenges are just weight training for your beautiful future~!",
    "Wah wah~! The idea of you succeeding makes me so incredibly happy~!",
    "You hold more magic inside you than any fairy tale could describe~!",
    "Breathe deeply, smile brightly, and remember: you're doing so well~!",
    "Your heart speaks the kindest language — let it keep talking~!",
    "Ehh~? Did you really think you couldn't do it? Watch yourself, friend~!",
    "On this day, I declare you unstoppable — please act accordingly~!",
    "You are bold, you are bright, you are beautiful in every single way~!",
    "Saa, let's make today so wonderful it gives yesterday something to envy~!",
    "Your inner light is reliable — it will guide you even in the dark~!",
    "Sometimes the bravest thing is to try one more time — please try~!",
    "Hihi~! Life loves people who keep going, and life loves you~!",
    "Each challenge you meet is proof you're built for something great~!",
    // ── 241–270  后半程冲刺 ──────────────────────────────────
    "Your energy, your spirit, your heart — all irreplaceable and all wonderful~!",
    "You carry so much love and so much strength — share both freely~!",
    "Mmn~ Today is a good day to be proud of who you are~!",
    "Wake up, smile up, level up — that's your powerful daily routine~!",
    "Fufufu~ The universe is always working overtime on your behalf~!",
    "You don't need luck — you have talent, heart, and real dedication~!",
    "Ooh~! Watching you grow into yourself is the most beautiful thing~!",
    "Every day you show up is a quiet act of extraordinary courage~!",
    "You are someone who makes things happen — go make something happen today~!",
    "Waaai~! Your potential doesn't have a ceiling — push on through~!",
    "Dreams are just goals with glitter — and yours are so very sparkly~!",
    "The effort you put in today is already changing your tomorrow~!",
    "Ara~! You're more resilient than you know — I've watched you prove it~!",
    "You don't just exist — you bloom, you glow, you inspire~!",
    "Hm hm~! Every hour of effort you invest multiplies in the future~!",
    "You are your greatest investment — choose yourself again today~!",
    "Uwaaah~! You handled that so gracefully — I'm genuinely in awe~!",
    "This world is richer, kinder, and brighter because of who you are~!",
    "Sou sou~! Keep at it — the breakthrough is closer than it seems~!",
    "Your warmth and your work ethic are a rare and precious combination~!",
    "Heehe~ You really have no idea how inspiring you are, do you~?",
    "You are the protagonist of a great story — keep adding beautiful chapters~!",
    "Keep dreaming giant dreams and taking tiny steps — it all adds up~!",
    "Maa ne~! You've already done the hardest part — you started~!",
    "You are not too much or too little — you are exactly, perfectly enough~!",
    "Shine as long and as brightly as you can — the world needs your light~!",
    "Kya~!! I just thought about all you've overcome and got emotional~!",
    "Growth is rarely loud — your quiet progress today is everything~!",
    "You trust yourself more each day — and that's a beautiful thing to witness~!",
    "Eeee~! Every day you give it your best, and that honestly means the world~!",
    // ── 271–300  深秋收获 ────────────────────────────────────
    "Your courage is showing in the smallest ways — and it's striking~!",
    "Fufu~ Challenges are just invitations to show what you're made of~!",
    "You are the author and the hero — write yourself a triumphant scene today~!",
    "Nnn~! Your perseverance is a superpower that impresses me every single day~!",
    "The seeds you're planting now will grow into the most beautiful garden~!",
    "Ehehe~! I adore how you show up for yourself — keep that up please~!",
    "You bring something unique and irreplaceable to everything you do~!",
    "Doki doki~! My excitement for your future literally cannot be contained~!",
    "Every step forward, however small, is still forward — celebrate it~!",
    "You are exactly the kind of person who makes the world a better place~!",
    "Uwnn~! The strength it takes to keep going — you have so much of it~!",
    "You've earned every good thing coming your way — welcome it openly~!",
    "Mmn! Your spark doesn't dim even on the cloudiest days — I notice~!",
    "Something incredible is built inside you — let today help it grow~!",
    "Yosh! Final quarter of the year — you have come so incredibly far~!",
    "You are not defined by your setbacks, you're defined by your comebacks~!",
    "Hehe~ Even when the path is unclear, your heart knows the way~!",
    "You motivate me just by watching you — and I'll never stop watching~!",
    "Mhm mhm~! You have so many reasons to feel proud — count a few today~!",
    "Every single day you are becoming more fully, beautifully yourself~!",
    "Kira~! End of year approaching and you're still shining — don't dim now~!",
    "You hold the pen to your own story — write something bold today~!",
    "Aa~ Just a reminder that your dream matters and so do you~!",
    "Waah~! The dedication you show every single day is seriously stunning~!",
    "You are so close to something wonderful — please don't stop here~!",
    "Your hustle today is your victory tomorrow — believe in the process~!",
    "Ehh~! You've already proved so much to yourself this year — let that sink in~!",
    "Tehe~! The glow-up is happening — maybe you can't see it, but I can~!",
    "Keep walking forward — every step is sacred, even the uncertain ones~!",
    "You build something beautiful with your life every single day~!",
    // ── 301–330  年末倒计时 ──────────────────────────────────
    "Ne ne~! Your commitment to yourself this year has been wonderful to witness~!",
    "Fuwa~! All your quiet efforts have been adding up to something miraculous~!",
    "You radiate a hope and warmth that touches everyone around you~!",
    "Haaah~! You've made it through so much — this next thing is nothing~!",
    "You are powered by something deeper than motivation — you have real heart~!",
    "Uwaaau~! You're in the home stretch — push with everything you have~!",
    "Belief in yourself is the best fuel — fill up on it today~!",
    "Ehhh~ You're writing a story worth telling — don't stop the pen now~!",
    "Your growth this year has been quiet, steady, and absolutely remarkable~!",
    "Saa~! The countdown to year's end — and you've been amazing all through it~!",
    "You deserve a round of applause for how you've carried yourself this year~!",
    "Fufufu~! I've been cheering for you every single day and I won't stop now~!",
    "You are the type of person great stories are written about — live it~!",
    "Heyyy~! Your smile, your effort, your heart — they haven't gone unnoticed~!",
    "One day at a time, you've built something you should be proud of~!",
    "Nnn~! You've grown so much this year — hug that progress close today~!",
    "Oooh, the universe has been recording every effort — the reward is coming~!",
    "You are genuinely one of the good ones — please keep being you~!",
    "Waai~! You've done hard things before and you'll do this one too~!",
    "Your best days are not behind you — they are ahead and they are bright~!",
    "Aa aa~! The finish line is in sight — run toward it with everything~!",
    "You've been so consistent, so brave, so wonderful this year~!",
    "Kira kira~! You shine brighter at the end of the year than the start~!",
    "Every lesson this year made you wiser, stronger, and more yourself~!",
    "Ehe~! You showed up for yourself when it mattered most — remember that~!",
    "Your journey isn't over — it's just entering an exciting new chapter~!",
    "Fufu~! Think of all the things you thought you couldn't do — and did~!",
    "You have more courage in your little finger than most have in total~!",
    "Kyaa~! Look at who you've become — I am so absolutely uncontrollably proud~!",
    "Every small kindness you gave yourself this year was well deserved~!",
    // ── 331–365  年末收尾与新年展望 ──────────────────────────
    "Nn~! From day one to here — the growth is breathtaking, truly~!",
    "You've kept your spark alive through everything — that's incredible~!",
    "Ne~! Dream big for next year — you have so much evidence you can achieve it~!",
    "Your energy, your soul, your warmth — they are beautiful and needed~!",
    "Uwaa~! Look at everything you've built, survived, and created — bow~!",
    "You took on this year and you're finishing it — that's a triumph~!",
    "Hehe~! Next year's you is going to be even more incredible — believe it~!",
    "Ahhh~! I'm so honored to have cheered for someone as amazing as you~!",
    "Every single day this year, you showed up — and that changes everything~!",
    "Fuwaaa~! You are magic wrapped in a person, and I mean that deeply~!",
    "Saa~! Gather your wins, learn from your losses, and face ahead~!",
    "You've earned your rest — and also your pride~!",
    "Ara ara~! Each challenge you faced this year made you more formidable~!",
    "Your dedication through difficult seasons is your greatest testament~!",
    "Ehehe~! You are almost at year's end — look back and smile at what you did~!",
    "You carried so much this year and never stopped moving — extraordinary~!",
    "Ne ne~! Whatever comes next year, you are more than ready to meet it~!",
    "You are such a beautiful force of nature — the world is lucky~!",
    "Uwuu~! You gave this year everything — now let it give back to you~!",
    "The courage it took to be you this year could fill a library~!",
    "Kya~!! You are ending this year stronger than you started — notice that~!",
    "Fufu~! Of all the things this year brought, your growth was the best~!",
    "You've done well, you've lived fully, you've faced bravely — be proud~!",
    "Sou sou~! Tomorrow is New Year's Eve — you made it, you really made it~!",
    "Happy last day of the year! You are amazing — I'll cheer for you again next year~!"
];
